"""empty message

Revision ID: 6692fc705e4c
Revises: 
Create Date: 2019-11-19 01:48:54.353862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6692fc705e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('average',
    sa.Column('avg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('avg')
    )
    op.create_table('spots',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('taken', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('spot_id')
    )
    op.create_table('timestampchange',
    sa.Column('spot_detail_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('spot_detail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timestampchange')
    op.drop_table('spots')
    op.drop_table('average')
    # ### end Alembic commands ###
